#! /bin/sh

. ./start_functions.sh

http_servers="svr-http"

if test $# -eq 1; then
    eid=$1
else
    for i in $http_servers
    do
        eid=`himage -e $i`
        if test $? -ne 0 ;then
            echo "Cannot find node $i"
            exit 2
        fi
    done
fi

if test $# -eq 1; then
    eid=$1
    isEidRunning $eid
else
    eid=`isNodeRunning svr-http`
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

if isOSfreebsd; then
    hasPackage www $eid '^lighttpd-'
fi

for serv in $http_servers
do
    echo "Starting http server on $serv..."
    h=${serv}@${eid}
    docker_container=`himage -v $h`
    himage $h mkdir -p /usr/local/etc/lighttpd
    himage $h mkdir -p /var/log/lighttpd
    if isOSlinux; then
        himage $h chown -R www-data:www-data /var/log/lighttpd
    else
        himage $h chown -R www:www /var/log/lighttpd
    fi

    docker cp WEB_files/${serv}.lighttpd.conf $docker_container:/usr/local/etc/lighttpd/lighttpd.conf
    himage $h chmod 755 /usr/local/etc/lighttpd/lighttpd.conf
    if isOSlinux; then
        docker cp WEB_files/www.${serv} $docker_container:/root
        himage -b $h lighttpd -f /usr/local/etc/lighttpd/lighttpd.conf
    else
        docker cp -r WEB_files/www.${serv} $docker_container:/root
        himage $h lighttpd -f /usr/local/etc/lighttpd/lighttpd.conf
    fi
done
