#! /bin/sh

. ./start_functions.sh

dns_servers="svr-dns"

hosts="neighbor svr-http"

if test $# -eq 1; then
    eid=$1
    isEidRunning $eid
else
    eid=`isNodeRunning svr-dns`
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

cd DNS_files

for i in $dns_servers
do
    container=`himage -v $i@$eid`

    # Stop named on all DNS servers
    himage ${i}@${eid} killall -9 named > /dev/null 2>&1

    himage $i@$eid mkdir -p /var/named/etc/namedb
    for f in $i/*
    do
      docker cp ${f} $container:/var/named/etc/namedb
    done

    # Start named on all DNS servers
    echo Starting named on $i...
    himage $i@$eid named -c /var/named/etc/namedb/named.conf
done

echo
echo Copy/Create resolv.conf on clients:
for i in $hosts
do
  echo $i
  himage $i@$eid echo "`cat resolv.$i`" > /etc/resolv.conf
done

echo
echo Create empty resolv.conf on DNS servers:
for i in $dns_servers
do
    echo $i
    himage $i@$eid echo "" > /etc/resolv.conf
done

