#!/usr/bin/env bash
# server

set -e          # fail fast
set -o pipefail # fail through pipe
# set -x

sandnet_dir=$(cd $(dirname $0); cd ..; pwd)
source $sandnet_dir/script/common.sh

cd $sandnet_dir

say "updating"
$sandnet_dir/script/update

say "initializing services"
systemctl restart docker.service ovs-vswitchd.service ovsdb-server.service

say "running sandnet"
sudo imunes -b -e sandnet $sandnet_dir/sandnet-imunes.imn | indent

trap stop_experiment INT

function stop_experiment() {
  echo
  say "CTRL-C received. Stopping experiment..."
  sudo imunes -b -e sandnet
}

say "disable tcp segmentation offload and checksums due linux bug"
echo
echo "see more at http://stackoverflow.com/questions/26716722/tcp-receives-packets-but-it-ignores-them" | indent
echo "and https://tech.vijayp.ca/linux-kernel-bug-delivers-corrupt-tcp-ip-data-to-mesos-kubernetes-docker-containers-4986f88f7a19#.wlcj6kccb" | indent
echo

sudo ethtool -K sandnet-n0 tso off | indent
sudo ethtool --offload sandnet-n0 rx off tx off | indent
sudo ethtool -K sandnet-n0-ext0 tso off | indent
sudo ethtool --offload sandnet-n0-ext0 rx off tx off | indent

say "imunes experiment is running... press ctrl+c to stop"
while true; do sleep 1; done
