#!/usr/bin/env bash
# server

set -e          # fail fast
set -o pipefail # fail through pipe
# set -x

sandnet_dir=$(cd $(dirname $0); cd ..; pwd)
source $sandnet_dir/script/common.sh

cd $sandnet_dir

say "updating"
$sandnet_dir/script/update

say "running services"
for service in docker.service ovs-vswitchd.service ovsdb-server.service; do
  if ! systemctl status $service > /dev/null; then
    systemctl restart $service
  fi
done

say "running sandnet"
sudo imunes -b -e sandnet $sandnet_dir/sandnet-imunes.imn | indent

trap stop_experiment INT
function stop_experiment() {
  echo
  say "CTRL-C received. Stopping experiment..."
  sudo imunes -b -e sandnet
}

say "disable tcp segmentation offload and checksums due linux bug"
echo
echo "see more at http://stackoverflow.com/questions/26716722/tcp-receives-packets-but-it-ignores-them" | indent
echo "and https://tech.vijayp.ca/linux-kernel-bug-delivers-corrupt-tcp-ip-data-to-mesos-kubernetes-docker-containers-4986f88f7a19#.wlcj6kccb" | indent
echo

for ifname in sandnet-{n0-ext0,n1-e0,n1-e1,n1-e2,n3-e0,n3-e1,n4-e0,n4-e1}; do
  sudo ethtool -K $ifname tso off | indent
  sudo ethtool --offload $ifname rx off tx off | indent
done

say "starting sandnet services"
cd $sandnet_dir/services
sudo $sandnet_dir/services/start_http | indent
sudo $sandnet_dir/services/start_dns | indent
#sudo $sandnet_dir/services/start_mail
echo
echo "NOTE: your resolv service may not work. Try to reconnect" | indent
echo
cd $sandnet_dir

say "imunes experiment is running... press ctrl+c to stop"
while true; do sleep 1; done
